openapi: 3.0.0
info:
  title: API Progressão de Alunos de Música
  version: 1.0.0
  description: API para acompanhamento da progressão de alunos de música.
servers:
  - url: http://localhost:3000
paths:
  /instructors/register:
    post:
      summary: Registrar instrutor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Instrutor registrado
  /instructors/login:
    post:
      summary: Login instrutor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token JWT
  /students/register:
    post:
      summary: Registrar aluno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Aluno registrado
  /students/login:
    post:
      summary: Login aluno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Token JWT
  /lessons:
    post:
      summary: Criar lição
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Lição criada
    get:
      summary: Listar lições
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de lições
  /progress:
    post:
      summary: Registrar progresso do aluno
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentId:
                  type: integer
                lessonId:
                  type: integer
      responses:
        '201':
          description: Progresso registrado
  /students/progress/{studentId}:
    get:
      summary: Consultar progresso do aluno
      security:
        - bearerAuth: []
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Progresso do aluno
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
