openapi: 3.0.0
info:
  title: API Progressão de Alunos de Música
  version: 1.0.0
  description: API REST para acompanhamento da progressão de alunos de música.
servers:
  - url: http://localhost:3000
paths:
  /api/instructor/register:
    post:
      summary: Registro de instrutor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Instrutor registrado
  /api/instructor/login:
    post:
      summary: Login de instrutor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login realizado com sucesso
  /api/student/register:
    post:
      summary: Registro de aluno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Aluno registrado
  /api/student/login:
    post:
      summary: Login de aluno
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login realizado com sucesso
  /api/lessons:
    post:
      summary: Registro de lição (instrutor)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Lição registrada
    get:
      summary: Listar lições
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de lições
  /api/progress:
    get:
      summary: Consultar progresso do aluno
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Progresso do aluno
  /api/progress/complete:
    post:
      summary: Registrar lição realizada pelo aluno
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lessonId:
                  type: string
      responses:
        '201':
          description: Lição marcada como realizada
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
